spring.application.name=parasoft-someip-demo-app
server.port=9998

# ActiveMQ configuration
spring.activemq.broker-url=tcp://0.0.0.0:61616
spring.activemq.embedded-broker-name=embedded-broker
spring.activemq.pool.enabled=false